import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
data = pd.read_csv("https://raw.githubusercontent.com/taghizadeh598/Image_processing/main/weather.csv")
data.to_csv("weather.csv")
plt.figure(figsize=(10, 6))
sns.barplot(x="Date.Month", y="Data.Precipitation", data=data)
plt.title('Precipitation Over Time (Month)')
plt.xlabel('Date')
plt.ylabel('Precipitation (mm)')
plt.show()
plt.figure(figsize=(10, 6))
sns.barplot(x="Date.Week of", y="Data.Precipitation", data=data)
plt.title('Precipitation Over Time (Day)')
plt.xlabel('Week of')
plt.ylabel('Precipitation (mm)')
plt.show()
plt.figure(figsize=(10, 6))
sns.barplot(x="Date.Month", y="Data.Temperature.Avg Temp", data=data)
plt.title('Average Temperature (Month)')
plt.xlabel('Month')
plt.ylabel('Average Temperature (Celsius)')
plt.show()
plt.figure(figsize=(10, 6))
sns.barplot(x="Date.Month", y="Data.Temperature.Max Temp", data=data)
plt.title('Average Max Temperature (Month)')
plt.xlabel('Month')
plt.ylabel('Max Temperature (Celsius)')
plt.show()
plt.figure(figsize=(10, 6))
sns.barplot(x="Date.Month", y="Data.Temperature.Min Temp", data=data)
plt.title('Average Min Temperature (Month)')
plt.xlabel('Month')
plt.ylabel('Min Temperature (Celsius)')
plt.show()
plt.figure(figsize=(10, 6))
sns.barplot(x="Date.Month", y="Data.Wind.Direction", data=data)
plt.title('Average Wind Direction (Month)')
plt.xlabel('Month')
plt.ylabel('Wind Direction (axis)')
plt.show()
plt.figure(figsize=(10, 6))
sns.barplot(x="Date.Month", y="Data.Wind.Speed", data=data)
plt.title('Average Wind Speed (Month)')
plt.xlabel('Date')
plt.ylabel('Wind Speed (km/s)')
plt.show()
plt.figure(figsize=(100, 20))
sns.barplot(x="Station.State", y="Data.Temperature.Avg Temp", data=data)
plt.title('Average Temperature (State)')
plt.xlabel('State')
plt.ylabel('Average Temperature (Celsius)')
plt.show()
plt.figure(figsize=(100, 20))
sns.barplot(x="Station.State", y="Data.Wind.Speed", data=data)
plt.title('Average Wind Speed (State)')
plt.xlabel('State')
plt.ylabel('Wind Speed (km/s)')
plt.show()
plt.figure(figsize=(10, 6))
sns.scatterplot(x="Date.Month", y="Data.Precipitation", data=data)
plt.title('Precipitation Over Time (Month)')
plt.xlabel('Date')
plt.ylabel('Precipitation (mm)')
plt.show()
plt.figure(figsize=(10, 6))
sns.scatterplot(x="Date.Week of", y="Data.Precipitation", data=data)
plt.title('Precipitation Over Time (Day)')
plt.xlabel('Week of')
plt.ylabel('Precipitation (mm)')
plt.show()
plt.figure(figsize=(10, 6))
sns.scatterplot(x="Date.Month", y="Data.Temperature.Avg Temp", data=data)
plt.title('Average Temperature (Month)')
plt.xlabel('Month')
plt.ylabel('Average Temperature (Celsius)')
plt.show()
plt.figure(figsize=(10, 6))
sns.scatterplot(x="Date.Month", y="Data.Temperature.Max Temp", data=data)
plt.title('Average Max Temperature (Month)')
plt.xlabel('Month')
plt.ylabel('Max Temperature (Celsius)')
plt.show()
plt.figure(figsize=(10, 6))
sns.scatterplot(x="Date.Month", y="Data.Temperature.Min Temp", data=data)
plt.title('Average Min Temperature (Month)')
plt.xlabel('Month')
plt.ylabel('Min Temperature (Celsius)')
plt.show()
plt.figure(figsize=(10, 6))
sns.scatterplot(x="Date.Month", y="Data.Wind.Direction", data=data)
plt.title('Average Wind Direction (Month)')
plt.xlabel('Month')
plt.ylabel('Wind Direction (axis)')
plt.show()
plt.figure(figsize=(10, 6))
sns.scatterplot(x="Date.Month", y="Data.Wind.Speed", data=data)
plt.title('Average Wind Speed (Month)')
plt.xlabel('Date')
plt.ylabel('Wind Speed (km/s)')
plt.show()
plt.figure(figsize=(100, 20))
sns.scatterplot(x="Station.State", y="Data.Temperature.Avg Temp", data=data)
plt.title('Average Temperature (State)')
plt.xlabel('State')
plt.ylabel('Average Temperature (Celsius)')
plt.show()
plt.figure(figsize=(100, 20))
sns.scatterplot(x="Station.State", y="Data.Wind.Speed", data=data)
plt.title('Average Wind Speed (State)')
plt.xlabel('State')
plt.ylabel('Wind Speed (km/s)')
plt.show()
